version: '3'
services:
  dockereurekaserver:
    image: wennaisong/dockereurekaserver
    restart: always
    ports:
      - 8761:8761
    container_name: dockereurekaserver

  dockereurakaregister:
    image: wennaisong/dockereurakaregister
    restart: always
    ports:
      - 8763:8763
    links:
      - dockereurekaserver